# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 565)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-image: url(:/bj/img/bj.jpg);\n"
"    background-position:center;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setStyleSheet("background:none;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background:none;")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        self.toolButton_2.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(251, 255, 184, 170);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget)
        self.toolButton_4.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton_4.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(251, 255, 184, 170);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 2, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(215, 255, 224, 150);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget)
        self.toolButton_3.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton_3.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(215, 255, 224, 150);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget)
        self.toolButton_6.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton_6.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(251, 255, 184, 170);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 3, 2, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget)
        self.toolButton_5.setMinimumSize(QtCore.QSize(200, 100))
        self.toolButton_5.setStyleSheet("border-radius:20px;\n"
"background-color: rgba(215, 255, 224, 150);\n"
"font-size:16px;\n"
"font-weight:900;\n"
"color: rgb(76, 76, 76);")
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">抑</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">郁</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">症</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">状</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">因</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">素</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">分</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">析</span></p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "抑郁各项指标分析"))
        self.toolButton_4.setText(_translate("MainWindow", "经济压力与抑郁分析"))
        self.toolButton.setText(_translate("MainWindow", "学习压力抑郁分析"))
        self.toolButton_3.setText(_translate("MainWindow", "抑郁与自杀年龄分析"))
        self.toolButton_6.setText(_translate("MainWindow", "学习压力与年龄抑郁"))
        self.toolButton_5.setText(_translate("MainWindow", "饮食与抑郁分析"))
import MyWindow_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
